"""The shipped INI and the eleven translation files for HUD Position Manager."""
import ast, os, re

R = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OR_GENDIST = os.path.join(os.path.dirname(R), "HUDPositionManagerOR", "tools", "gen-dist.py")
os.makedirs(R + r"\dist\SKSE\Plugins", exist_ok=True)
os.makedirs(R + r"\dist\Interface\Translations", exist_ok=True)


def element_rows():
    """Every row of the element table: (key, name, menu, moveWith, stretch, fades, bar). A row may span lines."""
    src = open(R + r"\source\Elements.cpp", encoding="utf-8").read()
    rows = []
    for m in re.finditer(r'^\s*\{ "([A-Za-z]+)", "([^"]+)", \{', src, re.M):
        i, depth = m.end(), 1
        while depth:   # the parts list's closing brace
            depth += {"{": 1, "}": -1}.get(src[i], 0)
            i += 1
        j, depth = i, 1
        while depth:   # the row's closing brace
            depth += {"{": 1, "}": -1}.get(src[j], 0)
            j += 1
        rest = [t.strip() for t in src[i:j - 1].split(",") if t.strip()]
        rest += ["nullptr", "nullptr", "false", "false", "false"][len(rest):]
        q = lambda t: None if t == "nullptr" else t.strip('"')
        rows.append((m.group(1), m.group(2), q(rest[0]), q(rest[1]), rest[2] == "true", rest[3] == "true", rest[4] == "true"))
    return rows


rows = element_rows()
_count = len(re.findall(r'^\s*\{ "[A-Za-z]+", "', open(R + r"\source\Elements.cpp", encoding="utf-8").read(), re.M))
assert len(rows) == _count, f"parsed {len(rows)} element rows of {_count} in Elements.cpp - fix the parser"
elements = [(k, n) for k, n, *_ in rows]

ini = ["; HUD Position Manager - its settings page in the Apocrypha Menu Framework edits this file for you.",
       "; fX / fY move an element: a percentage of the screen (right / down positive), added to where the HUD puts it.",
       "; fScale is times the size the HUD gives it, about the element's centre; fLength / fHeight stretch one side on top of it.",
       "; bHide hides the element. iShow: 0 always (as the game decides), 1 only in combat, 2 only out of combat, 3 the HUD toggle,",
       "; 4 only indoors, 5 only outdoors, 6 only with a weapon drawn, 8 only while sneaking, 9 (crosshair, sneak eye) when it matters.",
       "; bAlwaysVisible (the elements the game fades on its own): 1 keeps it shown while you play.",
       "; sMoveWith names another element (Health, Stamina, ...) whose offset this one also takes: a widget beside a bar follows it.",
       "", "[General]", "; 1 = apply the layout below, 0 = every element back where the HUD puts it", "bEnabled=1",
       "; 1 = Magicka and Stamina move with Health (the three bars as one block)", "bLinkBars=1",
       "; 1 = widgets a UI places around the bars (Norden UI: STB Widgets, TrueHUD's bars) move with the bars", "bLinkWidgets=1",
       "; 1 = the bars stay shown while you play instead of fading out when full", "bAlwaysVisible=0",
       "; 1 = Free placement: the move sliders go past the screen's edges", "bUnlocked=0",
       "; 1 = Show (in / out of combat) fades an element instead of hiding it at once", "bFade=0",
       "; fade speeds 1..20: half a full fade a second per step (10 = about 0.2 s, 5 = about 0.4 s)", "iFadeInSpeed=10", "iFadeOutSpeed=5",
       "; opacity in percent of an element faded by Show: out of its moment (min) and in it (max)", "iOpacityMin=0", "iOpacityMax=100",
       "; Log level: 0 trace, 1 debug, 2 info, 3 warn, 4 error. Raise to 0 for a bug report.", "uLogLevel=2",
       "", "[Immersive]", "; the HUD toggle (ImmersiveHUD's way): 1 = a key shows and hides every element whose iShow is 3", "bEnabled=0",
       "; the key (a DirectInput scan code; 45 = X) and the controller button (an XInput mask; 0 = none) - set them on the page",
       "iToggleKey=45", "iToggleButton=0", "; 1 = shown only while the key is held", "bHoldMode=0",
       "; seconds a press shows the HUD (0..10, 0 = a press toggles it)", "fDisplaySeconds=0.0",
       "; 1 = shown after loading", "bStartVisible=0", "; 1 = while shown, the bars the game fades when full stay shown", "bHoldBarsWhenShown=1",
       "; 1 = the toggle's elements also show in combat / while a weapon or spell is drawn", "bShowInCombat=1", "bShowWeaponDrawn=1",
       "", "[PlayerBars]", "; HPM's own Health / Magicka / Stamina bars (TrueHUD's player widget): 1 = on (hide the game's on their tabs)",
       "bEnabled=0", "; each bar: 0 never, 1 when it changes, 2 in combat, 3 when another bar shows, 4 always",
       "uHealthMode=1", "uMagickaMode=1", "uStaminaMode=1", "; 1 = the recent loss lingers behind the fill, this many seconds",
       "bPhantom=1", "fPhantomSeconds=0.75", "; 1 = the mount's stamina while riding", "bMountStamina=1",
       "; 1 = Survival Mode's reduction drawn at the bar's end", "bSurvivalPenalty=1", "; 1 = the numbers on the bar", "bShowValues=0",
       "", "[RecentLoot]", "; a short list of what you just picked up (TrueHUD's recent loot): 1 = on", "bEnabled=0",
       "; 1 = the game's own \"X added\" notification is hidden (0: both show)", "bHideVanillaMessage=0",
       "; how long an entry stays (seconds), and at most this many (1..6)", "fSeconds=5.0", "uMaxCount=6",
       "", "[BossBars]", "; a large bar for the boss fighting you - a dragon, or its location's boss (TrueHUD's boss bar): 1 = on",
       "bEnabled=0", "; within this distance (game units); 1 = its level beside the bar", "fMaxDistance=4096", "bShowLevel=1",
       "", "[InfoBars]", "; health bars over the characters around you (TrueHUD's info bars): 1 = on", "bEnabled=0",
       "; enemies: 0 never, 1 in a fight or when hit, 2 always; followers: 0 never, 1 while you fight, 2 always; everyone else: 0 never, 1 when hit, 2 always",
       "uDisplayHostiles=1", "uDisplayTeammates=1", "uDisplayOthers=1", "bShowName=1", "bShowLevel=1",
       "; at most this many bars, out to this distance (game units), this high above the head, this big", "uMaxCount=10",
       "fMaxDistance=2048", "fOffsetZ=20", "fScale=1.00", "; 1 = smaller farther away", "bScaleWithDistance=1",
       "", "[Group]", "; the Combined widgets tab: these elements (comma-separated keys) move as one by fX / fY", "sMembers=", "fX=0", "fY=0"]
for key, _name, _menu, follow, stretch, fades, _bar in rows:
    ini += ["", f"[{key}]", "fX=0", "fY=0", "fScale=1", "fLength=1", "fHeight=1", "bHide=0", "iShow=0"]
    if fades:
        ini += ["bAlwaysVisible=0"]
    ini += [f"sMoveWith={follow or ''}"]
open(R + r"\dist\SKSE\Plugins\HUDPositionManager.ini", "w", encoding="utf-8", newline="").write("\r\n".join(ini) + "\r\n")

# key -> [english, japanese, korean, chinese, russian, german, french, spanish, italian, polish, czech]
T = {
    "HPM_Intro": ["Move, resize or hide each part of the HUD. Changes show in the HUD at once and are saved automatically.",
                  "HUDの各要素を移動・拡大縮小・非表示にできます。変更はすぐにHUDへ反映され、自動で保存されます。",
                  "HUD의 각 요소를 이동하거나 크기를 바꾸거나 숨깁니다. 변경 사항은 즉시 HUD에 반영되고 자동으로 저장됩니다.",
                  "移动、缩放或隐藏 HUD 的每个部分。更改会立即显示在 HUD 中，并自动保存。",
                  "Перемещайте, масштабируйте или скрывайте любую часть интерфейса. Изменения сразу видны в интерфейсе и сохраняются автоматически.",
                  "Verschiebe, skaliere oder verstecke jeden Teil des HUD. Änderungen erscheinen sofort im HUD und werden automatisch gespeichert.",
                  "Déplacez, redimensionnez ou masquez chaque partie de l'ATH. Les changements s'affichent aussitôt et sont enregistrés automatiquement.",
                  "Mueve, cambia de tamaño u oculta cada parte del HUD. Los cambios se ven al instante en el HUD y se guardan automáticamente.",
                  "Sposta, ridimensiona o nascondi ogni parte dell'HUD. Le modifiche appaiono subito nell'HUD e vengono salvate automaticamente.",
                  "Przesuwaj, skaluj lub ukrywaj każdy element HUD. Zmiany widać od razu, a zapis jest automatyczny.",
                  "Přesouvejte, měňte velikost nebo skryjte každou část HUD. Změny se v HUD projeví hned a ukládají se automaticky."],
    "HPM_Enabled": ["Apply my layout", "レイアウトを適用", "내 배치 적용", "应用我的布局", "Применять мою раскладку", "Mein Layout anwenden",
                    "Appliquer ma disposition", "Aplicar mi diseño", "Applica il mio layout", "Stosuj mój układ", "Použít mé rozvržení"],
    "HPM_EnabledHint": ["off: every element back where the HUD puts it", "オフ: すべての要素をHUDの既定位置に戻す", "끄기: 모든 요소가 HUD 기본 위치로 돌아갑니다",
                        "关闭：所有元素回到 HUD 默认位置", "выкл.: все элементы на своих обычных местах", "aus: jedes Element wieder dort, wo das HUD es hinsetzt",
                        "désactivé : chaque élément revient à sa place d'origine", "desactivado: cada elemento vuelve a donde lo pone el HUD",
                        "disattivato: ogni elemento torna dove lo mette l'HUD", "wyłączone: każdy element wraca na swoje miejsce",
                        "vypnuto: každý prvek se vrátí tam, kam ho dává HUD"],
    "HPM_NoHud": ["The HUD has not been shown yet - load a game to see this element.", "HUDはまだ表示されていません。ゲームをロードするとこの要素が表示されます。",
                  "아직 HUD가 표시되지 않았습니다. 게임을 불러오면 이 요소를 볼 수 있습니다.", "HUD 尚未显示——载入游戏后即可看到此元素。",
                  "Интерфейс ещё не показан - загрузите игру, чтобы увидеть этот элемент.", "Das HUD wurde noch nicht angezeigt - lade ein Spiel, um dieses Element zu sehen.",
                  "L'ATH n'est pas encore affiché - chargez une partie pour voir cet élément.", "El HUD aún no se ha mostrado; carga una partida para ver este elemento.",
                  "L'HUD non è ancora stato mostrato: carica una partita per vedere questo elemento.", "HUD nie był jeszcze wyświetlony - wczytaj grę, aby zobaczyć ten element.",
                  "HUD se zatím nezobrazil - načtěte hru, abyste tento prvek viděli."],
    "HPM_NotFound": ["Not found in your HUD: the HUD you use may not have this element, or names it differently. Its settings are kept but do nothing.",
                     "お使いのHUDに見つかりません。このHUDにはこの要素がないか、別の名前になっている可能性があります。設定は保持されますが効果はありません。",
                     "사용 중인 HUD에서 찾을 수 없습니다. 이 요소가 없거나 다른 이름일 수 있습니다. 설정은 유지되지만 적용되지 않습니다.",
                     "在你的 HUD 中未找到：你使用的 HUD 可能没有此元素，或名称不同。其设置会保留但不起作用。",
                     "Не найден в вашем интерфейсе: в нём может не быть этого элемента или он называется иначе. Настройки сохраняются, но ни на что не влияют.",
                     "In deinem HUD nicht gefunden: Dein HUD hat dieses Element vielleicht nicht oder nennt es anders. Die Einstellungen bleiben erhalten, bewirken aber nichts.",
                     "Introuvable dans votre ATH : il n'a peut-être pas cet élément ou le nomme autrement. Ses réglages sont conservés mais sans effet.",
                     "No se encuentra en tu HUD: puede que no tenga este elemento o que lo llame de otra forma. Sus ajustes se conservan pero no hacen nada.",
                     "Non trovato nel tuo HUD: potrebbe non avere questo elemento o chiamarlo in altro modo. Le impostazioni restano ma non hanno effetto.",
                     "Nie znaleziono w twoim HUD: może nie mieć tego elementu lub nazywa go inaczej. Ustawienia zostają zachowane, ale nic nie robią.",
                     "Ve vašem HUD nenalezeno: nemusí tento prvek mít nebo ho pojmenovává jinak. Nastavení zůstává, ale nemá účinek."],
    "HPM_Found": ["In your HUD - changes show at once.", "HUDにあります。変更はすぐに反映されます。", "HUD에 있습니다. 변경 사항이 즉시 반영됩니다.",
                  "存在于你的 HUD 中——更改立即生效。", "Есть в вашем интерфейсе - изменения видны сразу.", "In deinem HUD - Änderungen erscheinen sofort.",
                  "Présent dans votre ATH - les changements s'affichent aussitôt.", "Está en tu HUD: los cambios se ven al instante.",
                  "Presente nel tuo HUD: le modifiche appaiono subito.", "Jest w twoim HUD - zmiany widać od razu.", "Je ve vašem HUD - změny se projeví hned."],
    "HPM_MoveX": ["Move left / right", "左右に移動", "좌우 이동", "左右移动", "Сдвиг влево / вправо", "Nach links / rechts",
                  "Déplacer à gauche / droite", "Mover izquierda / derecha", "Sposta a sinistra / destra", "Przesuń w lewo / prawo", "Posun vlevo / vpravo"],
    "HPM_MoveY": ["Move up / down", "上下に移動", "상하 이동", "上下移动", "Сдвиг вверх / вниз", "Nach oben / unten",
                  "Déplacer en haut / bas", "Mover arriba / abajo", "Sposta su / giù", "Przesuń w górę / dół", "Posun nahoru / dolů"],
    "HPM_Size": ["Size", "サイズ", "크기", "大小", "Размер", "Größe", "Taille", "Tamaño", "Dimensione", "Rozmiar", "Velikost"],
    "HPM_Hide": ["Hide", "非表示", "숨기기", "隐藏", "Скрыть", "Ausblenden", "Masquer", "Ocultar", "Nascondi", "Ukryj", "Skrýt"],
    "HPM_ResetOne": ["Reset this element", "この要素をリセット", "이 요소 초기화", "重置此元素", "Сбросить этот элемент", "Dieses Element zurücksetzen",
                     "Réinitialiser cet élément", "Restablecer este elemento", "Ripristina questo elemento", "Resetuj ten element", "Obnovit tento prvek"],
    "HPM_ResetAll": ["Reset every element", "すべての要素をリセット", "모든 요소 초기화", "重置所有元素", "Сбросить все элементы", "Alle Elemente zurücksetzen",
                     "Réinitialiser tous les éléments", "Restablecer todos los elementos", "Ripristina tutti gli elementi", "Resetuj wszystkie elementy", "Obnovit všechny prvky"],
    "HPM_El_Health": ["Health", "体力", "체력", "生命值", "Здоровье", "Gesundheit", "Santé", "Salud", "Salute", "Zdrowie", "Zdraví"],
    "HPM_El_Magicka": ["Magicka", "マジカ", "매지카", "法力值", "Магия", "Magicka", "Magie", "Magia", "Magicka", "Magia", "Magie"],
    "HPM_El_Stamina": ["Stamina", "スタミナ", "지구력", "耐力值", "Запас сил", "Ausdauer", "Vigueur", "Aguante", "Vigore", "Wytrzymałość", "Výdrž"],
    "HPM_El_LeftCharge": ["Left charge meter", "左手チャージメーター", "왼손 충전 게이지", "左手充能条", "Заряд левой руки", "Ladeanzeige links",
                          "Jauge de charge gauche", "Medidor de carga izquierdo", "Carica sinistra", "Wskaźnik naładowania - lewa", "Nabití - levá"],
    "HPM_El_RightCharge": ["Right charge meter", "右手チャージメーター", "오른손 충전 게이지", "右手充能条", "Заряд правой руки", "Ladeanzeige rechts",
                           "Jauge de charge droite", "Medidor de carga derecho", "Carica destra", "Wskaźnik naładowania - prawa", "Nabití - pravá"],
    "HPM_El_Compass": ["Compass", "コンパス", "나침반", "罗盘", "Компас", "Kompass", "Boussole", "Brújula", "Bussola", "Kompas", "Kompas"],
    "HPM_El_Crosshair": ["Crosshair", "照準", "조준점", "准星", "Прицел", "Fadenkreuz", "Réticule", "Punto de mira", "Mirino", "Celownik", "Zaměřovač"],
    "HPM_El_EnemyHealth": ["Enemy health", "敵の体力", "적 체력", "敌人生命值", "Здоровье врага", "Gegnergesundheit", "Santé de l'ennemi",
                           "Salud del enemigo", "Salute del nemico", "Zdrowie wroga", "Zdraví nepřítele"],
    "HPM_El_StealthMeter": ["Stealth meter", "隠密メーター", "은신 게이지", "潜行指示", "Индикатор скрытности", "Schleichanzeige", "Indicateur de discrétion",
                            "Indicador de sigilo", "Indicatore di furtività", "Wskaźnik skradania", "Ukazatel plížení"],
    "HPM_El_Subtitles": ["Subtitles", "字幕", "자막", "字幕", "Субтитры", "Untertitel", "Sous-titres", "Subtítulos", "Sottotitoli", "Napisy", "Titulky"],
    "HPM_El_ArrowInfo": ["Ammo count", "矢弾の数", "탄약 수", "弹药数量", "Боеприпасы", "Munitionsanzeige", "Munitions", "Munición", "Munizioni", "Amunicja", "Střelivo"],
    "HPM_El_Messages": ["Notifications", "通知", "알림", "通知", "Уведомления", "Benachrichtigungen", "Notifications", "Notificaciones", "Notifiche", "Powiadomienia", "Oznámení"],
    "HPM_El_QuestUpdate": ["Quest updates", "クエスト更新", "퀘스트 갱신", "任务更新", "Обновления заданий", "Questaktualisierungen", "Mises à jour de quête",
                           "Actualizaciones de misión", "Aggiornamenti delle missioni", "Aktualizacje zadań", "Aktualizace úkolů"],
    "HPM_El_ActivatePrompt": ["Activate prompt", "アクティベート表示", "상호작용 안내", "交互提示", "Подсказка действия", "Aktivierungshinweis",
                              "Invite d'activation", "Indicador de activar", "Prompt di attivazione", "Podpowiedź akcji", "Výzva k aktivaci"],
    "HPM_El_LocationText": ["Location name", "場所の名前", "장소 이름", "地点名称", "Название локации", "Ortsname", "Nom du lieu", "Nombre del lugar",
                            "Nome del luogo", "Nazwa miejsca", "Název místa"],
    "HPM_WidgetClosed": ["This widget is not showing: the mod that adds it is not installed, or has it switched off. Its settings are kept.",
                         "このウィジェットは表示されていません。追加するMODが入っていないか、オフになっています。設定は保持されます。",
                         "이 위젯은 표시되지 않습니다. 추가하는 모드가 설치되지 않았거나 꺼져 있습니다. 설정은 유지됩니다.",
                         "此小部件未显示：添加它的模组未安装或已关闭。其设置会保留。",
                         "Этот виджет не показан: добавляющий его мод не установлен или выключил его. Настройки сохраняются.",
                         "Dieses Widget wird nicht angezeigt: Die Mod, die es hinzufügt, ist nicht installiert oder hat es ausgeschaltet. Die Einstellungen bleiben erhalten.",
                         "Ce widget n'est pas affiché : le mod qui l'ajoute n'est pas installé ou l'a désactivé. Ses réglages sont conservés.",
                         "Este widget no se muestra: el mod que lo añade no está instalado o lo tiene desactivado. Sus ajustes se conservan.",
                         "Questo widget non è visibile: la mod che lo aggiunge non è installata o lo ha disattivato. Le impostazioni restano.",
                         "Ten widżet nie jest wyświetlany: dodający go mod nie jest zainstalowany lub go wyłączył. Ustawienia zostają zachowane.",
                         "Tento widget se nezobrazuje: mod, který ho přidává, není nainstalován nebo ho vypnul. Nastavení zůstává."],
    "HPM_MoveWith": ["Move with", "一緒に動かす", "함께 이동", "跟随移动", "Двигать вместе с", "Mitbewegen mit", "Suivre", "Mover con", "Sposta con", "Przesuwaj z", "Posouvat s"],
    "HPM_MoveWithNone": ["Nothing - on its own", "なし (単独)", "없음 - 단독", "无——独立", "Ничем - сам по себе", "Nichts - eigenständig", "Rien - indépendant",
                         "Nada - por sí solo", "Niente - da solo", "Nic - samodzielnie", "Nic - samostatně"],
    "HPM_El_CombinedCharge": ["Combined charge meters", "統合チャージメーター", "통합 충전 게이지", "合并充能条", "Общий заряд", "Kombinierte Ladeanzeige",
                              "Jauges de charge combinées", "Medidores de carga combinados", "Cariche combinate", "Połączone wskaźniki naładowania", "Společné nabití"],
    "HPM_El_ShoutMeter": ["Shout meter", "シャウトメーター", "용언 게이지", "龙吼指示条", "Шкала Криков", "Schreianzeige", "Jauge de cri", "Medidor de grito",
                          "Barra dell'urlo", "Wskaźnik okrzyku", "Ukazatel pokřiku"],
    "HPM_El_LevelUp": ["Level-up meter", "レベルアップメーター", "레벨 업 게이지", "升级指示", "Шкала уровня", "Stufenanzeige", "Jauge de niveau", "Medidor de nivel",
                       "Indicatore di livello", "Wskaźnik poziomu", "Ukazatel úrovně"],
    "HPM_El_AnimLetters": ["Word wall letters", "言葉の壁の文字", "용언 벽 글자", "龙语墙文字", "Буквы Стены слов", "Wortwand-Buchstaben", "Lettres du mur de mots",
                           "Letras del muro de palabras", "Lettere del muro delle parole", "Litery ściany słów", "Písmena zdi slov"],
    "HPM_El_Clock": ["Clock", "時計", "시계", "时钟", "Часы", "Uhr", "Horloge", "Reloj", "Orologio", "Zegar", "Hodiny"],
    "HPM_LinkBars": ["Move the three bars together", "3本のバーを一緒に動かす", "세 바를 함께 이동", "三条状态条一起移动", "Двигать три полосы вместе",
                     "Die drei Leisten gemeinsam bewegen", "Déplacer les trois barres ensemble", "Mover las tres barras juntas", "Sposta insieme le tre barre",
                     "Przesuwaj trzy paski razem", "Posouvat tři lišty společně"],
    "HPM_LinkBarsHint": ["Magicka and Stamina move with Health", "マジカとスタミナが体力と一緒に動く", "매지카와 지구력이 체력과 함께 이동", "法力和耐力随生命移动",
                         "Магия и запас сил следуют за здоровьем", "Magicka und Ausdauer folgen der Gesundheit", "La magie et la vigueur suivent la santé",
                         "La magia y el aguante siguen a la salud", "Magicka e vigore seguono la salute", "Magia i wytrzymałość podążają za zdrowiem",
                         "Magie a výdrž následují zdraví"],
    "HPM_LinkWidgets": ["Widgets around the bars move with them", "バー周りのウィジェットも一緒に動かす", "바 주변 위젯도 함께 이동", "状态条周围的小部件随之移动",
                        "Виджеты у полос двигаются вместе с ними", "Widgets um die Leisten bewegen sich mit", "Les widgets autour des barres les suivent",
                        "Los widgets alrededor de las barras las siguen", "I widget intorno alle barre le seguono", "Widżety wokół pasków przesuwają się z nimi",
                        "Widgety u lišt se posouvají s nimi"],
    "HPM_LinkWidgetsHint": ["for a UI that places widgets around the bars, like Norden UI", "Norden UIのようにバーの周りにウィジェットを置くUI向け",
                            "Norden UI처럼 바 주변에 위젯을 두는 UI용", "适用于像 Norden UI 这样在状态条周围放置小部件的界面",
                            "для интерфейсов, размещающих виджеты у полос, как Norden UI", "für ein UI, das Widgets um die Leisten legt, wie Norden UI",
                            "pour une interface qui place des widgets autour des barres, comme Norden UI",
                            "para una interfaz que coloca widgets alrededor de las barras, como Norden UI",
                            "per un'interfaccia che dispone widget intorno alle barre, come Norden UI",
                            "dla interfejsu, który umieszcza widżety wokół pasków, jak Norden UI",
                            "pro rozhraní, které dává widgety kolem lišt, jako Norden UI"],
    "HPM_El_QuestMarker": ["Floating quest marker", "浮遊クエストマーカー", "떠 있는 퀘스트 표시", "浮动任务标记", "Плавающий маркер задания",
                           "Schwebende Questmarkierung", "Marqueur de quête flottant", "Marcador de misión flotante", "Indicatore di missione fluttuante",
                           "Pływający znacznik zadania", "Plovoucí značka úkolu"],
    "HPM_El_Temperature": ["Temperature meter", "体温メーター", "체온 게이지", "体温条", "Шкала температуры", "Temperaturanzeige", "Jauge de température",
                           "Medidor de temperatura", "Indicatore della temperatura", "Wskaźnik temperatury", "Ukazatel teploty"],
    "HPM_El_Breath": ["Breath meter", "息継ぎメーター", "호흡 게이지", "呼吸条", "Шкала дыхания", "Atemanzeige", "Jauge de souffle",
                      "Medidor de aliento", "Indicatore del respiro", "Wskaźnik oddechu", "Ukazatel dechu"],
    "HPM_El_CastingBar": ["Casting bar", "詠唱バー", "시전 바", "施法条", "Полоса заклинания", "Zauberleiste", "Barre d'incantation",
                          "Barra de lanzamiento", "Barra di lancio", "Pasek rzucania", "Ukazatel sesílání"],
    "HPM_El_InfoGold": ["Gold", "所持金", "골드", "金币", "Золото", "Gold", "Or", "Oro", "Oro", "Złoto", "Zlato"],
    "HPM_El_InfoWeight": ["Carry weight", "所持重量", "소지 무게", "负重", "Переносимый вес", "Traglast", "Poids transporté",
                          "Peso cargado", "Peso trasportato", "Udźwig", "Nosnost"],
    "HPM_Style": ["Style", "スタイル", "스타일", "样式", "Стиль", "Stil", "Style", "Estilo", "Stile", "Styl", "Styl"],
    "HPM_StyleHint": ["Two looks for the same information - pick the one you like. A UI mod can reskin either.",
                      "同じ情報を2通りの見た目で表示します。好きな方を選んでください。どちらもUI MODで変更できます。",
                      "같은 정보를 두 가지 모양으로 보여 줍니다. 원하는 쪽을 고르세요. 둘 다 UI 모드로 바꿀 수 있습니다.",
                      "同一信息的两种外观，选你喜欢的。两种都可由界面模组重新换肤。",
                      "Два вида одних и тех же сведений - выберите любой. Оба можно перерисовать модом интерфейса.",
                      "Zwei Ansichten derselben Angabe - wähle die, die dir gefällt. Ein UI-Mod kann beide umgestalten.",
                      "Deux présentations de la même information - choisissez celle qui vous plaît. Un mod d'interface peut habiller l'une ou l'autre.",
                      "Dos aspectos para la misma información: elige el que prefieras. Un mod de interfaz puede cambiar cualquiera de los dos.",
                      "Due aspetti per la stessa informazione: scegli quello che preferisci. Una mod dell'interfaccia può ridisegnarli entrambi.",
                      "Dwa wyglądy tej samej informacji - wybierz ten, który wolisz. Mod interfejsu może zmienić oba.",
                      "Dva vzhledy téže informace - vyberte ten, který se vám líbí. Mod rozhraní může změnit oba."],
    "HPM_StyleBar": ["Bar - the number in front of a bar", "バー - バーの前に数値", "바 - 막대 앞에 숫자", "条形 - 数字在条前",
                     "Полоса - число перед полосой", "Leiste - die Zahl vor einer Leiste", "Barre - le nombre devant une barre",
                     "Barra - el número delante de una barra", "Barra - il numero davanti a una barra", "Pasek - liczba przed paskiem",
                     "Lišta - číslo před lištou"],
    "HPM_StyleBadge": ["Badge - the number in a badge, a ring round it", "バッジ - バッジの中に数値、周りにリング",
                       "배지 - 배지 안에 숫자, 둘레에 고리", "徽章 - 数字在徽章中，外围一圈环",
                       "Значок - число в значке, вокруг кольцо", "Abzeichen - die Zahl in einem Abzeichen, ein Ring darum",
                       "Insigne - le nombre dans un insigne, un anneau autour", "Insignia - el número en una insignia, con un anillo alrededor",
                       "Distintivo - il numero in un distintivo, con un anello intorno", "Odznaka - liczba w odznace, wokół pierścień",
                       "Odznak - číslo v odznaku, kolem něj prstenec"],
    "HPM_El_InfoTime": ["Game time", "ゲーム内時刻", "게임 시간", "游戏时间", "Игровое время", "Spielzeit", "Heure du jeu", "Hora del juego",
                        "Ora di gioco", "Czas w grze", "Herní čas"],
    "HPM_El_ShoutCooldown": ["Shout cooldown", "シャウトの回復", "외침 재사용 대기", "龙吼冷却", "Перезарядка Крика", "Schrei-Abklingzeit",
                             "Recharge du Cri", "Recarga del grito", "Ricarica dell'Urlo", "Odnowienie Krzyku", "Obnova pokřiku"],
    "HPM_Fade": ["Fade instead of hiding at once", "すぐに隠さずフェードする", "즉시 숨기지 않고 서서히 사라지기", "渐隐而非立即隐藏",
                 "Плавно скрывать, а не сразу", "Ausblenden statt sofort verstecken", "Fondu au lieu de masquer d'un coup",
                 "Desvanecer en lugar de ocultar de golpe", "Dissolvenza invece di nascondere subito", "Wygaszaj zamiast ukrywać od razu",
                 "Prolínat místo okamžitého skrytí"],
    "HPM_FadeHint": ["Show (in / out of combat) fades the element in and out instead of hiding it at once.",
                     "表示（戦闘中／戦闘外）で、要素をすぐに隠さずフェードイン・フェードアウトさせます。",
                     "표시(전투 중 / 전투 외)가 요소를 즉시 숨기지 않고 서서히 나타나고 사라지게 합니다.",
                     "显示（战斗中 / 战斗外）会让元素渐入渐出，而不是立即隐藏。",
                     "«Показ» (в бою / вне боя) плавно проявляет и скрывает элемент, а не убирает его сразу.",
                     "Anzeigen (im / außerhalb des Kampfes) blendet das Element ein und aus, statt es sofort zu verstecken.",
                     "Afficher (en / hors combat) fait apparaître et disparaître l'élément en fondu au lieu de le masquer d'un coup.",
                     "Mostrar (en / fuera de combate) hace aparecer y desaparecer el elemento gradualmente en lugar de ocultarlo de golpe.",
                     "Mostra (in / fuori combattimento) fa comparire e scomparire l'elemento in dissolvenza invece di nasconderlo subito.",
                     "Pokazywanie (w walce / poza walką) płynnie pokazuje i wygasza element zamiast ukrywać go od razu.",
                     "Zobrazení (v boji / mimo boj) prvek plynule zobrazí a skryje místo okamžitého skrytí."],
    "HPM_FadeIn": ["Fade-in speed", "フェードインの速さ", "나타나는 속도", "渐入速度", "Скорость появления", "Einblendgeschwindigkeit",
                   "Vitesse d'apparition", "Velocidad de aparición", "Velocità di comparsa", "Szybkość pojawiania", "Rychlost objevení"],
    "HPM_FadeOut": ["Fade-out speed", "フェードアウトの速さ", "사라지는 속도", "渐出速度", "Скорость исчезновения", "Ausblendgeschwindigkeit",
                    "Vitesse de disparition", "Velocidad de desaparición", "Velocità di scomparsa", "Szybkość wygaszania", "Rychlost zmizení"],
    "HPM_FadeSpeedHint": ["Higher is faster: 10 fades in about 0.2 seconds, 5 in about 0.4.",
                          "大きいほど速くなります。10 で約 0.2 秒、5 で約 0.4 秒です。",
                          "높을수록 빠릅니다. 10은 약 0.2초, 5는 약 0.4초입니다.",
                          "数值越大越快：10 约 0.2 秒，5 约 0.4 秒。",
                          "Чем больше, тем быстрее: 10 — около 0,2 с, 5 — около 0,4 с.",
                          "Höher ist schneller: 10 blendet in etwa 0,2 Sekunden, 5 in etwa 0,4.",
                          "Plus c'est haut, plus c'est rapide : 10 en environ 0,2 seconde, 5 en environ 0,4.",
                          "Más alto es más rápido: 10 tarda unos 0,2 segundos, 5 unos 0,4.",
                          "Più alto è più veloce: 10 in circa 0,2 secondi, 5 in circa 0,4.",
                          "Wyżej znaczy szybciej: 10 to około 0,2 sekundy, 5 około 0,4.",
                          "Vyšší je rychlejší: 10 zhruba za 0,2 sekundy, 5 zhruba za 0,4."],
    "HPM_OpacityMin": ["Opacity when hidden", "隠れている時の不透明度", "숨겨졌을 때 불투명도", "隐藏时的不透明度", "Непрозрачность скрытого",
                       "Deckkraft, wenn verborgen", "Opacité une fois masqué", "Opacidad al ocultarse", "Opacità quando nascosto",
                       "Krycie po ukryciu", "Neprůhlednost při skrytí"],
    "HPM_OpacityMax": ["Opacity when shown", "表示されている時の不透明度", "표시될 때 불투명도", "显示时的不透明度", "Непрозрачность показанного",
                       "Deckkraft, wenn angezeigt", "Opacité une fois affiché", "Opacidad al mostrarse", "Opacità quando mostrato",
                       "Krycie po pokazaniu", "Neprůhlednost při zobrazení"],
    "HPM_OpacityHint": ["How see-through an element faded by Show is when out of its moment, and when in it.",
                        "表示でフェードする要素の、出番でない時と出番の時の透け具合です。",
                        "표시로 서서히 사라지는 요소가 해당 순간이 아닐 때와 해당 순간일 때 얼마나 비쳐 보이는지입니다.",
                        "由显示控制渐隐的元素，在不该出现时和该出现时的透明程度。",
                        "Насколько прозрачен элемент, которым управляет «Показ», вне своего момента и в нём.",
                        "Wie durchsichtig ein über Anzeigen ausgeblendetes Element außerhalb und während seines Moments ist.",
                        "La transparence d'un élément géré par Afficher, hors de son moment et pendant celui-ci.",
                        "Lo transparente que es un elemento atenuado por Mostrar fuera de su momento y durante él.",
                        "Quanto è trasparente un elemento sfumato da Mostra fuori dal suo momento e durante esso.",
                        "Jak przezroczysty jest element wygaszany przez Pokazywanie poza swoim momentem i w nim.",
                        "Jak průhledný je prvek prolínaný Zobrazením mimo svou chvíli a v ní."],
    "HPM_GroupImmersive": ["HUD toggle", "HUDトグル", "HUD 토글", "HUD 开关", "Переключатель интерфейса", "HUD-Umschalter", "Bascule de l'ATH", "Interruptor del HUD", "Interruttore dell'HUD", "Przełącznik HUD", "Přepínač HUD"],
    "HPM_Immersive": ["Immersive HUD", "没入型HUD", "몰입형 HUD", "沉浸式 HUD", "Иммерсивный интерфейс", "Immersives HUD", "ATH immersif", "HUD inmersivo", "HUD immersivo", "Immersyjny HUD", "Imerzivní HUD"],
    "HPM_ImmersiveHint": ["On: a key shows and hides every element whose Show is 'Follow the HUD toggle' - they fade out of sight while you explore and back when you press it.", "オン: 表示が「HUDトグルに従う」の要素をキーで表示・非表示にします。探索中は消え、キーを押すと戻ってきます。", "켜기: 표시가 'HUD 토글 따르기'인 모든 요소를 키로 보이고 숨깁니다. 탐험 중에는 사라지고 키를 누르면 돌아옵니다.", "开启：用一个键显示和隐藏所有“显示”设为“跟随 HUD 开关”的元素——探索时淡出，按下时重新出现。", "Вкл.: клавиша показывает и скрывает все элементы, у которых «Показывать» стоит на «По переключателю интерфейса»: они тают, пока вы исследуете, и возвращаются по нажатию.", "An: Eine Taste blendet jedes Element ein und aus, dessen Anzeigen auf „Dem HUD-Umschalter folgen“ steht - beim Erkunden verschwinden sie, auf Tastendruck kommen sie zurück.", "Activé : une touche affiche et masque chaque élément dont Afficher est réglé sur « Suivre la bascule de l'ATH » - ils s'effacent pendant l'exploration et reviennent quand vous appuyez.", "Activado: una tecla muestra y oculta cada elemento cuyo Mostrar es «Seguir el interruptor del HUD»: se desvanecen mientras exploras y vuelven al pulsarla.", "Attivo: un tasto mostra e nasconde ogni elemento il cui Mostra è «Segui l'interruttore dell'HUD» - svaniscono mentre esplori e tornano quando lo premi.", "Włączone: klawisz pokazuje i ukrywa każdy element, którego Pokazuj ustawiono na „Według przełącznika HUD” - znikają podczas zwiedzania i wracają po naciśnięciu.", "Zapnuto: klávesa zobrazí a skryje každý prvek, jehož Zobrazit je „Podle přepínače HUD“ - při průzkumu zmizí a po stisku se vrátí."],
    "HPM_IhudPresent": ["ImmersiveHUD is loaded too: both would fade the same parts of the HUD. Use one or the other.", "ImmersiveHUD も読み込まれています。両方がHUDの同じ部分をフェードさせてしまいます。どちらか一方を使ってください。", "ImmersiveHUD도 불러와져 있습니다. 둘 다 HUD의 같은 부분을 흐리게 하므로 하나만 사용하세요.", "ImmersiveHUD 也已加载：两者会淡出 HUD 的同样部分。请只用其中一个。", "ImmersiveHUD тоже загружен: оба будут скрывать одни и те же части интерфейса. Используйте что-то одно.", "ImmersiveHUD ist ebenfalls geladen: Beide würden dieselben Teile des HUD ausblenden. Nutze nur eines davon.", "ImmersiveHUD est chargé aussi : les deux estomperaient les mêmes parties de l'ATH. Utilisez l'un ou l'autre.", "ImmersiveHUD también está cargado: ambos desvanecerían las mismas partes del HUD. Usa uno u otro.", "Anche ImmersiveHUD è caricato: entrambi sfumerebbero le stesse parti dell'HUD. Usa l'uno o l'altro.", "ImmersiveHUD też jest wczytany: oba wygaszałyby te same części HUD. Używaj jednego z nich.", "ImmersiveHUD je načtený také: oba by prolínaly stejné části HUD. Používejte jen jeden."],
    "HPM_ToggleKey": ["Toggle key", "トグルキー", "토글 키", "开关键", "Клавиша переключения", "Umschalttaste", "Touche de bascule", "Tecla de alternar", "Tasto di attivazione", "Klawisz przełączania", "Klávesa přepínání"],
    "HPM_ToggleButton": ["Toggle button (controller)", "トグルボタン (コントローラー)", "토글 버튼 (컨트롤러)", "开关按钮（手柄）", "Кнопка переключения (геймпад)", "Umschaltknopf (Controller)", "Bouton de bascule (manette)", "Botón de alternar (mando)", "Pulsante di attivazione (controller)", "Przycisk przełączania (pad)", "Tlačítko přepínání (ovladač)"],
    "HPM_Unbound": ["none", "なし", "없음", "无", "нет", "keine", "aucune", "ninguna", "nessuno", "brak", "žádná"],
    "HPM_Bind": ["Bind", "割り当て", "지정", "绑定", "Назначить", "Belegen", "Assigner", "Asignar", "Assegna", "Przypisz", "Přiřadit"],
    "HPM_Clear": ["Clear", "解除", "해제", "清除", "Очистить", "Löschen", "Effacer", "Borrar", "Cancella", "Wyczyść", "Zrušit"],
    "HPM_PressKey": ["Press a key... (cancel)", "キーを押してください... (キャンセル)", "키를 누르세요... (취소)", "请按一个键……（取消）", "Нажмите клавишу... (отмена)", "Taste drücken... (Abbrechen)", "Appuyez sur une touche... (annuler)", "Pulsa una tecla... (cancelar)", "Premi un tasto... (annulla)", "Naciśnij klawisz... (anuluj)", "Stiskněte klávesu... (zrušit)"],
    "HPM_PressButton": ["Press a button... (cancel)", "ボタンを押してください... (キャンセル)", "버튼을 누르세요... (취소)", "请按一个按钮……（取消）", "Нажмите кнопку... (отмена)", "Knopf drücken... (Abbrechen)", "Appuyez sur un bouton... (annuler)", "Pulsa un botón... (cancelar)", "Premi un pulsante... (annulla)", "Naciśnij przycisk... (anuluj)", "Stiskněte tlačítko... (zrušit)"],
    "HPM_KeyReserved": ["That key is the menu's own. Press a different key.", "そのキーはメニュー自身が使っています。別のキーを押してください。", "그 키는 메뉴 자체에서 쓰는 키입니다. 다른 키를 누르세요.", "该键是菜单本身使用的。请按其他键。", "Эта клавиша занята самим меню. Нажмите другую.", "Diese Taste gehört dem Menü selbst. Drücke eine andere.", "Cette touche est celle du menu. Appuyez sur une autre touche.", "Esa tecla es del propio menú. Pulsa otra.", "Quel tasto è del menu stesso. Premine un altro.", "Ten klawisz należy do samego menu. Naciśnij inny.", "Tuto klávesu používá samotná nabídka. Stiskněte jinou."],
    "HPM_HoldMode": ["Hold to show", "押している間だけ表示", "누르는 동안만 표시", "按住时显示", "Показывать при удержании", "Halten zum Anzeigen", "Maintenir pour afficher", "Mantener para mostrar", "Tieni premuto per mostrare", "Przytrzymaj, aby pokazać", "Držet pro zobrazení"],
    "HPM_HoldModeHint": ["On: the HUD shows only while the key is held. Off: each press shows or hides it.", "オン: キーを押している間だけHUDが表示されます。オフ: 押すたびに表示・非表示が切り替わります。", "켜기: 키를 누르고 있는 동안에만 HUD가 표시됩니다. 끄기: 누를 때마다 보이거나 숨겨집니다.", "开启：仅在按住键时显示 HUD。关闭：每按一次显示或隐藏。", "Вкл.: интерфейс виден, только пока клавиша зажата. Выкл.: каждое нажатие показывает или скрывает его.", "An: Das HUD erscheint nur, solange die Taste gehalten wird. Aus: Jeder Druck blendet es ein oder aus.", "Activé : l'ATH ne s'affiche que tant que la touche est maintenue. Désactivé : chaque appui l'affiche ou le masque.", "Activado: el HUD solo se muestra mientras mantienes la tecla. Desactivado: cada pulsación lo muestra u oculta.", "Attivo: l'HUD appare solo mentre tieni premuto il tasto. Disattivo: ogni pressione lo mostra o lo nasconde.", "Włączone: HUD widać tylko, gdy trzymasz klawisz. Wyłączone: każde naciśnięcie go pokazuje lub ukrywa.", "Zapnuto: HUD je vidět jen při držení klávesy. Vypnuto: každý stisk ho zobrazí nebo skryje."],
    "HPM_DisplaySeconds": ["Show for", "表示時間", "표시 시간", "显示时长", "Показывать в течение", "Anzeigen für", "Afficher pendant", "Mostrar durante", "Mostra per", "Pokazuj przez", "Zobrazit na"],
    "HPM_DisplaySecondsHint": ["Above 0: a press shows the HUD for this long, then it fades again. 0: a press toggles it.", "0より大きい: 押すとこの時間だけHUDが表示され、また消えます。0: 押すたびに切り替わります。", "0보다 크면: 누르면 이 시간 동안 HUD가 표시된 뒤 다시 사라집니다. 0: 누를 때마다 전환됩니다.", "大于 0：按下后 HUD 显示这么久，然后再次淡出。0：按下即切换。", "Больше 0: нажатие показывает интерфейс на это время, затем он снова тает. 0: нажатие переключает его.", "Über 0: Ein Druck zeigt das HUD so lange, dann blendet es wieder aus. 0: Ein Druck schaltet es um.", "Au-dessus de 0 : un appui affiche l'ATH aussi longtemps, puis il s'estompe. 0 : un appui le bascule.", "Por encima de 0: una pulsación muestra el HUD este tiempo y luego se desvanece. 0: una pulsación lo alterna.", "Sopra 0: una pressione mostra l'HUD per questo tempo, poi svanisce di nuovo. 0: una pressione lo commuta.", "Powyżej 0: naciśnięcie pokazuje HUD na tyle czasu, potem znów znika. 0: naciśnięcie go przełącza.", "Nad 0: stisk zobrazí HUD na tuto dobu, pak opět zmizí. 0: stisk ho přepne."],
    "HPM_StartVisible": ["Shown after loading", "ロード後に表示", "불러온 뒤 표시", "载入后显示", "Виден после загрузки", "Nach dem Laden sichtbar", "Affiché après le chargement", "Visible tras cargar", "Visibile dopo il caricamento", "Widoczny po wczytaniu", "Zobrazený po načtení"],
    "HPM_HoldBars": ["Keep the bars up while shown", "表示中はバーを出したままにする", "표시 중에는 바 유지", "显示时保持状态条", "Не прятать полосы при показе", "Leisten beim Anzeigen sichtbar halten", "Garder les barres pendant l'affichage", "Mantener las barras mientras se muestra", "Tieni le barre mentre è mostrato", "Trzymaj paski, gdy HUD jest pokazany", "Držet lišty při zobrazení"],
    "HPM_HoldBarsHint": ["While the toggle shows the HUD, the bars the game fades when full stay shown.", "トグルでHUDが表示されている間、満タンになるとゲームが薄くするバーも表示されたままになります。", "토글로 HUD가 표시되는 동안, 가득 차면 게임이 흐리게 하는 바도 계속 표시됩니다.", "开关显示 HUD 时，游戏在满值时会淡出的状态条保持显示。", "Пока переключатель показывает интерфейс, полосы, которые игра скрывает при заполнении, остаются видны.", "Solange der Umschalter das HUD zeigt, bleiben die Leisten sichtbar, die das Spiel bei voller Anzeige ausblendet.", "Tant que la bascule affiche l'ATH, les barres que le jeu estompe quand elles sont pleines restent visibles.", "Mientras el interruptor muestra el HUD, las barras que el juego desvanece al llenarse siguen visibles.", "Finché l'interruttore mostra l'HUD, le barre che il gioco sfuma quando sono piene restano visibili.", "Gdy przełącznik pokazuje HUD, paski wygaszane przez grę po napełnieniu pozostają widoczne.", "Dokud přepínač ukazuje HUD, lišty, které hra při naplnění skrývá, zůstávají vidět."],
    "HPM_ImmersiveAll": ["Put the whole HUD on the toggle", "HUD全体をトグルに従わせる", "HUD 전체를 토글에 맡기기", "让整个 HUD 跟随开关", "Весь интерфейс по переключателю", "Das ganze HUD auf den Umschalter legen", "Mettre tout l'ATH sur la bascule", "Poner todo el HUD en el interruptor", "Metti tutto l'HUD sull'interruttore", "Cały HUD na przełącznik", "Celý HUD na přepínač"],
    "HPM_ImmersiveNone": ["Take it all off the toggle", "すべてトグルから外す", "모두 토글에서 빼기", "全部取消跟随开关", "Убрать всё с переключателя", "Alles vom Umschalter nehmen", "Tout retirer de la bascule", "Quitar todo del interruptor", "Togli tutto dall'interruttore", "Zdejmij wszystko z przełącznika", "Vše z přepínače odebrat"],
    "HPM_ShowImmersive": ["Follow the HUD toggle", "HUDトグルに従う", "HUD 토글 따르기", "跟随 HUD 开关", "По переключателю интерфейса", "Dem HUD-Umschalter folgen", "Suivre la bascule de l'ATH", "Seguir el interruptor del HUD", "Segui l'interruttore dell'HUD", "Według przełącznika HUD", "Podle přepínače HUD"],
    "HPM_ShowInterior": ["Only indoors", "屋内のみ", "실내에서만", "仅在室内", "Только в помещениях", "Nur drinnen", "Seulement en intérieur", "Solo en interiores", "Solo al chiuso", "Tylko we wnętrzach", "Jen uvnitř"],
    "HPM_ShowExterior": ["Only outdoors", "屋外のみ", "실외에서만", "仅在室外", "Только снаружи", "Nur draußen", "Seulement en extérieur", "Solo en exteriores", "Solo all'aperto", "Tylko na zewnątrz", "Jen venku"],
    "HPM_ShowWeapon": ["Only with a weapon drawn", "武器を構えている時のみ", "무기를 꺼냈을 때만", "仅在拔出武器时", "Только с оружием в руках", "Nur mit gezogener Waffe", "Seulement arme dégainée", "Solo con un arma desenfundada", "Solo con un'arma sfoderata", "Tylko z dobytą bronią", "Jen s tasenou zbraní"],
    "HPM_ShowSneak": ["Only while sneaking", "隠密中のみ", "은신 중에만", "仅在潜行时", "Только в скрытности", "Nur beim Schleichen", "Seulement en discrétion", "Solo con sigilo", "Solo in furtività", "Tylko podczas skradania", "Jen při plížení"],
    "HPM_ShowInCombatAll": ["Also shown in combat", "戦闘中も表示", "전투 중에도 표시", "战斗中也显示", "Также виден в бою", "Auch im Kampf sichtbar", "Affiché aussi en combat", "También visible en combate", "Visibile anche in combattimento", "Widoczny także w walce", "Zobrazit i v boji"],
    "HPM_ShowWeaponAll": ["Also shown with a weapon drawn", "武器を構えている時も表示", "무기를 꺼냈을 때도 표시", "拔出武器时也显示", "Также виден с оружием в руках", "Auch mit gezogener Waffe sichtbar", "Affiché aussi arme dégainée", "También visible con un arma desenfundada", "Visibile anche con un'arma sfoderata", "Widoczny także z dobytą bronią", "Zobrazit i s tasenou zbraní"],
    "HPM_ShowContextCross": ["When it matters - while aiming, attacking or casting", "必要な時だけ - 狙っている時、攻撃中、詠唱中",
                             "필요할 때만 - 조준, 공격, 시전 중", "需要时 - 瞄准、攻击或施法时", "Когда нужно - при прицеливании, атаке или чтении заклинания",
                             "Wenn es darauf ankommt - beim Zielen, Angreifen oder Zaubern", "Quand c'est utile - en visant, en attaquant ou en lançant un sort",
                             "Cuando importa - al apuntar, atacar o lanzar un hechizo", "Quando serve - mirando, attaccando o lanciando un incantesimo",
                             "Gdy ma znaczenie - przy celowaniu, ataku lub rzucaniu czaru", "Když je potřeba - při míření, útoku nebo sesílání kouzla"],
    "HPM_ShowContextEye": ["When it matters - as strong as the detection", "必要な時だけ - 気づかれ具合に応じた濃さ", "필요할 때만 - 들킨 정도만큼 진하게",
                           "需要时 - 浓淡随被察觉程度", "Когда нужно - тем заметнее, чем ближе обнаружение", "Wenn es darauf ankommt - so deutlich wie die Entdeckung",
                           "Quand c'est utile - aussi visible que la détection", "Cuando importa - tan visible como la detección",
                           "Quando serve - visibile quanto il rilevamento", "Gdy ma znaczenie - tak wyraźne jak wykrycie", "Když je potřeba - tak výrazné jako odhalení"],
    "HPM_TabBars": ["Bars and loot", "バーと戦利品", "바와 전리품", "状态条与战利品", "Полосы и добыча", "Leisten und Beute", "Barres et butin", "Barras y botín", "Barre e bottino", "Paski i łupy", "Lišty a kořist"],
    "HPM_TH_Present": ["TrueHUD is installed and already draws this. HPM's version stays off unless you turn it on here.", "TrueHUD が導入されており、すでにこれを表示しています。ここでオンにしない限りHPM版はオフのままです。", "TrueHUD가 설치되어 이미 이것을 표시합니다. 여기서 켜지 않는 한 HPM 버전은 꺼져 있습니다.", "已安装 TrueHUD，它已在显示此项。除非你在此开启，否则 HPM 的版本保持关闭。", "Установлен TrueHUD, и он уже это рисует. Версия HPM выключена, пока вы не включите её здесь.", "TrueHUD ist installiert und zeichnet dies bereits. Die HPM-Fassung bleibt aus, bis du sie hier einschaltest.", "TrueHUD est installé et affiche déjà ceci. La version de HPM reste désactivée sauf si vous l'activez ici.", "TrueHUD está instalado y ya dibuja esto. La versión de HPM sigue desactivada salvo que la actives aquí.", "TrueHUD è installato e lo disegna già. La versione di HPM resta spenta finché non la attivi qui.", "TrueHUD jest zainstalowany i już to rysuje. Wersja HPM pozostaje wyłączona, dopóki jej tu nie włączysz.", "TrueHUD je nainstalován a už to kreslí. Verze HPM zůstane vypnutá, dokud ji tu nezapnete."],
    "HPM_PB_Enabled": ["HPM's player bars", "HPMのプレイヤーバー", "HPM 플레이어 바", "HPM 玩家状态条", "Полосы игрока HPM", "HPM-Spielerleisten", "Barres du joueur de HPM", "Barras del jugador de HPM", "Barre del giocatore di HPM", "Paski gracza HPM", "Lišty hráče HPM"],
    "HPM_PB_EnabledHint": ["Health, Magicka and Stamina drawn by HPM, with recent loss and the Survival penalty. Hide the game's own bars on their tabs.", "体力・マジカ・スタミナをHPMが描画し、直近の減少とサバイバルのペナルティも表示します。ゲーム本来のバーは各タブで隠してください。", "체력, 매지카, 지구력을 HPM이 그리며 최근 감소량과 생존 페널티도 보여 줍니다. 게임 자체 바는 각 탭에서 숨기세요.", "由 HPM 绘制生命值、法力值和耐力值，并显示近期损失和生存模式惩罚。请在各自标签页隐藏游戏自带的状态条。", "Здоровье, магия и запас сил от HPM, с недавней потерей и штрафом режима выживания. Скройте игровые полосы на их вкладках.", "Gesundheit, Magicka und Ausdauer von HPM gezeichnet, mit letztem Verlust und Überlebensmalus. Blende die Leisten des Spiels auf ihren Reitern aus.", "Santé, magie et vigueur dessinées par HPM, avec la perte récente et la pénalité de survie. Masquez les barres du jeu dans leurs onglets.", "Salud, magia y aguante dibujados por HPM, con la pérdida reciente y la penalización de supervivencia. Oculta las barras del juego en sus pestañas.", "Salute, magicka e vigore disegnati da HPM, con la perdita recente e la penalità della sopravvivenza. Nascondi le barre del gioco nelle loro schede.", "Zdrowie, magia i wytrzymałość rysowane przez HPM, z ostatnią utratą i karą przetrwania. Ukryj paski gry na ich kartach.", "Zdraví, magie a výdrž kreslené HPM, s nedávnou ztrátou a postihem přežití. Lišty hry skryjte na jejich kartách."],
    "HPM_Never": ["Never", "表示しない", "표시 안 함", "从不", "Никогда", "Nie", "Jamais", "Nunca", "Mai", "Nigdy", "Nikdy"],
    "HPM_PB_ModeDynamic": ["When it changes", "変化した時", "변할 때", "变化时", "При изменении", "Bei Änderung", "Quand elle change", "Cuando cambia", "Quando cambia", "Gdy się zmienia", "Když se mění"],
    "HPM_PB_ModeWhenOther": ["When another bar shows", "他のバーが表示された時", "다른 바가 보일 때", "其他状态条显示时", "Когда видна другая полоса", "Wenn eine andere Leiste erscheint", "Quand une autre barre s'affiche", "Cuando se ve otra barra", "Quando appare un'altra barra", "Gdy widać inny pasek", "Když je vidět jiná lišta"],
    "HPM_PB_HealthMode": ["Show Health", "体力を表示", "체력 표시", "显示生命值", "Показывать здоровье", "Gesundheit anzeigen", "Afficher la santé", "Mostrar la salud", "Mostra la salute", "Pokazuj zdrowie", "Zobrazit zdraví"],
    "HPM_PB_MagickaMode": ["Show Magicka", "マジカを表示", "매지카 표시", "显示法力值", "Показывать магию", "Magicka anzeigen", "Afficher la magie", "Mostrar la magia", "Mostra la magicka", "Pokazuj magię", "Zobrazit magii"],
    "HPM_PB_StaminaMode": ["Show Stamina", "スタミナを表示", "지구력 표시", "显示耐力值", "Показывать запас сил", "Ausdauer anzeigen", "Afficher la vigueur", "Mostrar el aguante", "Mostra il vigore", "Pokazuj wytrzymałość", "Zobrazit výdrž"],
    "HPM_Phantom": ["Show recent loss", "直近の減少を表示", "최근 감소량 표시", "显示近期损失", "Показывать недавнюю потерю", "Letzten Verlust zeigen", "Afficher la perte récente", "Mostrar la pérdida reciente", "Mostra la perdita recente", "Pokazuj ostatnią utratę", "Zobrazit nedávnou ztrátu"],
    "HPM_PhantomSeconds": ["Recent loss lingers", "減少表示の残り時間", "감소량 유지 시간", "损失显示停留时间", "Задержка потери", "Verlust bleibt stehen", "Durée de la perte affichée", "Duración de la pérdida", "Durata della perdita", "Czas pokazywania utraty", "Doba zobrazení ztráty"],
    "HPM_PB_MountStamina": ["Mount's Stamina while riding", "騎乗中は馬のスタミナ", "탑승 중 탈것의 지구력", "骑乘时显示坐骑耐力", "Запас сил коня верхом", "Ausdauer des Reittiers beim Reiten", "Vigueur de la monture à cheval", "Aguante de la montura al cabalgar", "Vigore della cavalcatura in sella", "Wytrzymałość wierzchowca podczas jazdy", "Výdrž jezdeckého zvířete při jízdě"],
    "HPM_PB_SurvivalPenalty": ["Show the Survival penalty", "サバイバルのペナルティを表示", "생존 페널티 표시", "显示生存模式惩罚", "Показывать штраф выживания", "Überlebensmalus anzeigen", "Afficher la pénalité de survie", "Mostrar la penalización de supervivencia", "Mostra la penalità della sopravvivenza", "Pokazuj karę przetrwania", "Zobrazit postih přežití"],
    "HPM_PB_SurvivalPenaltyHint": ["In Survival Mode, the part of the bar that hunger, fatigue or cold has taken away is drawn at its end.", "サバイバルモードでは、空腹・疲労・寒さで失われた分がバーの端に表示されます。", "생존 모드에서 허기, 피로, 추위로 줄어든 부분이 바 끝에 표시됩니다.", "生存模式下，被饥饿、疲劳或寒冷夺走的部分显示在状态条末端。", "В режиме выживания часть полосы, отнятая голодом, усталостью или холодом, показана на её конце.", "Im Überlebensmodus wird der Teil, den Hunger, Erschöpfung oder Kälte nehmen, am Ende der Leiste gezeigt.", "En mode Survie, la part retirée par la faim, la fatigue ou le froid est dessinée au bout de la barre.", "En el modo Supervivencia, la parte que quitan el hambre, la fatiga o el frío se dibuja al final de la barra.", "In modalità Sopravvivenza, la parte tolta da fame, stanchezza o freddo è disegnata in fondo alla barra.", "W trybie przetrwania część paska zabrana przez głód, zmęczenie lub zimno jest rysowana na jego końcu.", "V režimu přežití je část lišty, kterou vzal hlad, únava nebo zima, vykreslena na jejím konci."],
    "HPM_ShowValues": ["Show the numbers", "数値を表示", "수치 표시", "显示数值", "Показывать числа", "Zahlen anzeigen", "Afficher les nombres", "Mostrar los números", "Mostra i numeri", "Pokazuj liczby", "Zobrazit čísla"],
    "HPM_El_PlayerHealth": ["Health bar (HPM)", "体力バー (HPM)", "체력 바 (HPM)", "生命条 (HPM)", "Полоса здоровья (HPM)", "Gesundheitsleiste (HPM)", "Barre de santé (HPM)", "Barra de salud (HPM)", "Barra della salute (HPM)", "Pasek zdrowia (HPM)", "Lišta zdraví (HPM)"],
    "HPM_El_PlayerMagicka": ["Magicka bar (HPM)", "マジカバー (HPM)", "매지카 바 (HPM)", "法力条 (HPM)", "Полоса магии (HPM)", "Magickaleiste (HPM)", "Barre de magie (HPM)", "Barra de magia (HPM)", "Barra della magicka (HPM)", "Pasek magii (HPM)", "Lišta magie (HPM)"],
    "HPM_El_PlayerStamina": ["Stamina bar (HPM)", "スタミナバー (HPM)", "지구력 바 (HPM)", "耐力条 (HPM)", "Полоса запаса сил (HPM)", "Ausdauerleiste (HPM)", "Barre de vigueur (HPM)", "Barra de aguante (HPM)", "Barra del vigore (HPM)", "Pasek wytrzymałości (HPM)", "Lišta výdrže (HPM)"],
    "HPM_IB_Enabled": ["Bars over characters", "キャラクターの頭上バー", "캐릭터 위 바", "角色头顶状态条", "Полосы над персонажами", "Leisten über Figuren", "Barres au-dessus des personnages", "Barras sobre los personajes", "Barre sopra i personaggi", "Paski nad postaciami", "Lišty nad postavami"],
    "HPM_IB_EnabledHint": ["A Health bar over enemies, followers and others near you, with their name and level.", "近くの敵・従者・その他の人物の頭上に、名前とレベル付きの体力バーを表示します。", "주변의 적, 동료, 기타 인물 위에 이름과 레벨이 있는 체력 바를 표시합니다.", "在附近的敌人、追随者和其他人头顶显示带名称和等级的生命条。", "Полоса здоровья над врагами, спутниками и другими рядом с вами, с именем и уровнем.", "Eine Gesundheitsleiste über Gegnern, Gefolgsleuten und anderen in deiner Nähe, mit Name und Stufe.", "Une barre de santé au-dessus des ennemis, compagnons et autres proches, avec leur nom et leur niveau.", "Una barra de salud sobre enemigos, seguidores y otros cerca de ti, con su nombre y nivel.", "Una barra della salute sopra nemici, seguaci e altri vicino a te, con nome e livello.", "Pasek zdrowia nad wrogami, towarzyszami i innymi w pobliżu, z imieniem i poziomem.", "Lišta zdraví nad nepřáteli, společníky a ostatními poblíž, se jménem a úrovní."],
    "HPM_IB_OnCombat": ["When a fight starts", "戦闘が始まった時", "전투가 시작될 때", "战斗开始时", "Когда начинается бой", "Wenn ein Kampf beginnt", "Quand un combat commence", "Cuando empieza una pelea", "Quando inizia uno scontro", "Gdy zaczyna się walka", "Když začne boj"],
    "HPM_IB_OnHit": ["When hit", "攻撃が当たった時", "맞았을 때", "被击中时", "При попадании", "Bei Treffer", "Quand touché", "Al recibir un golpe", "Quando colpito", "Po trafieniu", "Při zásahu"],
    "HPM_IB_DisplayHostiles": ["Enemies", "敵", "적", "敌人", "Враги", "Gegner", "Ennemis", "Enemigos", "Nemici", "Wrogowie", "Nepřátelé"],
    "HPM_IB_DisplayTeammates": ["Followers", "従者", "동료", "追随者", "Спутники", "Gefolgsleute", "Compagnons", "Seguidores", "Seguaci", "Towarzysze", "Společníci"],
    "HPM_IB_DisplayOthers": ["Everyone else", "その他", "그 외", "其他人", "Остальные", "Alle anderen", "Tous les autres", "Todos los demás", "Tutti gli altri", "Wszyscy inni", "Všichni ostatní"],
    "HPM_IB_DisplayName": ["Name", "名前", "이름", "名称", "Имя", "Name", "Nom", "Nombre", "Nome", "Imię", "Jméno"],
    "HPM_IB_IndicatorLevel": ["Level number", "レベルの数値", "레벨 숫자", "等级数字", "Число уровня", "Stufenzahl", "Numéro de niveau", "Número de nivel", "Numero di livello", "Liczba poziomu", "Číslo úrovně"],
    "HPM_MaxCount": ["Most at once", "同時表示の最大数", "동시 표시 최대 수", "同时显示上限", "Не больше одновременно", "Höchstens gleichzeitig", "Maximum à la fois", "Máximo a la vez", "Massimo contemporaneamente", "Najwyżej naraz", "Nejvýše najednou"],
    "HPM_IB_MaxDistance": ["Farthest distance", "最大距離", "최대 거리", "最远距离", "Наибольшее расстояние", "Größte Entfernung", "Distance maximale", "Distancia máxima", "Distanza massima", "Największa odległość", "Největší vzdálenost"],
    "HPM_IB_OffsetZ": ["Height above", "上方の高さ", "위쪽 높이", "上方高度", "Высота над", "Höhe darüber", "Hauteur au-dessus", "Altura por encima", "Altezza sopra", "Wysokość nad", "Výška nad"],
    "HPM_IB_ScaleDistance": ["Smaller with distance", "距離に応じて小さく", "거리에 따라 작게", "随距离缩小", "Меньше вдали", "Kleiner mit Entfernung", "Plus petit au loin", "Más pequeño con la distancia", "Più piccolo con la distanza", "Mniejszy z odległością", "Menší se vzdáleností"],
    "HPM_BB_Enabled": ["Boss bars", "ボスバー", "보스 바", "首领状态条", "Полосы боссов", "Bossleisten", "Barres de boss", "Barras de jefe", "Barre dei boss", "Paski bossów", "Lišty bossů"],
    "HPM_BB_EnabledHint": ["A large bar on the screen for dragons, dragon priests and other bosses while you fight them.", "ドラゴン、ドラゴンプリーストなどのボスと戦っている間、画面に大きなバーを表示します。", "드래곤, 드래곤 사제 등 보스와 싸우는 동안 화면에 큰 바를 표시합니다.", "与巨龙、龙祭司等首领战斗时，在屏幕上显示大状态条。", "Большая полоса на экране, пока вы сражаетесь с драконами, жрецами драконов и другими боссами.", "Eine große Leiste auf dem Bildschirm, solange du gegen Drachen, Drachenpriester und andere Bosse kämpfst.", "Une grande barre à l'écran pendant les combats contre les dragons, prêtres-dragons et autres boss.", "Una barra grande en pantalla mientras luchas contra dragones, sacerdotes dragón y otros jefes.", "Una grande barra sullo schermo mentre combatti draghi, sacerdoti del drago e altri boss.", "Duży pasek na ekranie podczas walki ze smokami, smoczymi kapłanami i innymi bossami.", "Velká lišta na obrazovce, dokud bojujete s draky, dračími kněžími a jinými bossy."],
    "HPM_El_BossBars": ["Boss bars", "ボスバー", "보스 바", "首领状态条", "Полосы боссов", "Bossleisten", "Barres de boss", "Barras de jefe", "Barre dei boss", "Paski bossów", "Lišty bossů"],
    "HPM_RL_Enabled": ["Recent loot list", "最近の戦利品リスト", "최근 전리품 목록", "最近获得列表", "Список недавней добычи", "Liste der letzten Beute", "Liste du butin récent", "Lista de botín reciente", "Elenco del bottino recente", "Lista ostatnich łupów", "Seznam nedávné kořisti"],
    "HPM_RL_EnabledHint": ["Each item you pick up is listed for a few seconds with its count.", "拾ったアイテムが個数付きで数秒間リストに表示されます。", "주운 아이템이 개수와 함께 몇 초 동안 목록에 표시됩니다.", "拾取的每件物品会连同数量在列表中显示几秒。", "Каждый подобранный предмет несколько секунд виден в списке вместе с количеством.", "Jeder aufgehobene Gegenstand steht ein paar Sekunden mit seiner Anzahl in der Liste.", "Chaque objet ramassé est listé quelques secondes avec sa quantité.", "Cada objeto que recoges aparece unos segundos en la lista con su cantidad.", "Ogni oggetto raccolto resta nell'elenco per qualche secondo con la sua quantità.", "Każdy podniesiony przedmiot widnieje na liście przez kilka sekund z liczbą sztuk.", "Každý sebraný předmět je na pár sekund v seznamu i s počtem."],
    "HPM_RL_HideVanilla": ["Hide the game's 'added' message", "ゲームの「入手」メッセージを隠す", "게임의 '획득' 메시지 숨기기", "隐藏游戏的“获得”消息", "Скрывать сообщение игры «добавлено»", "Die „hinzugefügt“-Meldung des Spiels ausblenden", "Masquer le message « ajouté » du jeu", "Ocultar el mensaje «añadido» del juego", "Nascondi il messaggio «aggiunto» del gioco", "Ukryj komunikat gry „dodano”", "Skrýt hlášení hry „přidáno“"],
    "HPM_El_RecentLoot": ["Recent loot", "最近の戦利品", "최근 전리품", "最近获得", "Недавняя добыча", "Letzte Beute", "Butin récent", "Botín reciente", "Bottino recente", "Ostatnie łupy", "Nedávná kořist"],
    "HPM_Seconds": ["Seconds shown", "表示秒数", "표시 시간(초)", "显示秒数", "Секунд на экране", "Sekunden sichtbar", "Secondes affichées", "Segundos visibles", "Secondi visibili", "Sekundy widoczności", "Sekund zobrazení"],
    "HPM_El_BowDraw": ["Bow draw", "弓の引き絞り", "활시위 당기기", "拉弓", "Натяжение лука", "Bogenspannung", "Tension de l'arc",
                       "Tensado del arco", "Tensione dell'arco", "Naciąg łuku", "Natažení luku"],
    "HPM_El_ShoutCharge": ["Shout charge", "シャウトの溜め", "외침 충전", "龙吼蓄力", "Зарядка Крика", "Schrei-Aufladung",
                           "Charge du Cri", "Carga del grito", "Carica dell'Urlo", "Ładowanie Krzyku", "Nabití pokřiku"],
    "HPM_El_InfoResist": ["Resistances", "耐性", "저항력", "抗性", "Сопротивления", "Widerstände", "Résistances", "Resistencias",
                          "Resistenze", "Odporności", "Odolnosti"],
    "HPM_El_InfoEquip": ["Equipped items", "装備中のアイテム", "장착한 아이템", "已装备物品", "Экипировка", "Ausgerüstete Gegenstände",
                         "Objets équipés", "Objetos equipados", "Oggetti equipaggiati", "Wyposażone przedmioty", "Vybavené předměty"],
    "HPM_El_InfoPlayTime": ["Play time", "プレイ時間", "플레이 시간", "游玩时间", "Время в игре", "Gespielte Zeit", "Temps de jeu",
                            "Tiempo de juego", "Tempo di gioco", "Czas gry", "Odehraný čas"],
    "HPM_El_InfoEffects": ["Active effects", "有効な効果", "활성 효과", "生效中的效果", "Активные эффекты", "Aktive Effekte",
                           "Effets actifs", "Efectos activos", "Effetti attivi", "Aktywne efekty", "Aktivní efekty"],
    "HPM_El_SurvHunger": ["Hunger", "空腹", "허기", "饥饿", "Голод", "Hunger", "Faim", "Hambre", "Fame", "Głód", "Hlad"],
    "HPM_El_SurvFatigue": ["Fatigue", "疲労", "피로", "疲劳", "Усталость", "Erschöpfung", "Fatigue", "Fatiga", "Stanchezza",
                           "Zmęczenie", "Únava"],
    "HPM_El_SurvCold": ["Cold", "寒さ", "추위", "寒冷", "Холод", "Kälte", "Froid", "Frío", "Freddo", "Zimno", "Zima"],
    "HPM_El_InfoLevel": ["Level", "レベル", "레벨", "等级", "Уровень", "Stufe", "Niveau", "Nivel", "Livello", "Poziom", "Úroveň"],
    "HPM_El_Detection": ["Detection meter", "検知メーター", "탐지 게이지", "侦测条", "Шкала обнаружения", "Entdeckungsanzeige", "Jauge de détection",
                         "Medidor de detección", "Indicatore di rilevamento", "Wskaźnik wykrycia", "Ukazatel odhalení"],
    "HPM_El_TrueHUDHealth": ["TrueHUD health bar", "TrueHUD 体力バー", "TrueHUD 체력 바", "TrueHUD 生命条", "Полоса здоровья TrueHUD", "TrueHUD-Gesundheitsleiste",
                             "Barre de santé TrueHUD", "Barra de salud de TrueHUD", "Barra della salute TrueHUD", "Pasek zdrowia TrueHUD", "Lišta zdraví TrueHUD"],
    "HPM_El_TrueHUDMagicka": ["TrueHUD magicka bar", "TrueHUD マジカバー", "TrueHUD 매지카 바", "TrueHUD 法力条", "Полоса магии TrueHUD", "TrueHUD-Magickaleiste",
                              "Barre de magie TrueHUD", "Barra de magia de TrueHUD", "Barra della magicka TrueHUD", "Pasek magii TrueHUD", "Lišta magie TrueHUD"],
    "HPM_El_TrueHUDStamina": ["TrueHUD stamina bar", "TrueHUD スタミナバー", "TrueHUD 지구력 바", "TrueHUD 耐力条", "Полоса запаса сил TrueHUD", "TrueHUD-Ausdauerleiste",
                              "Barre de vigueur TrueHUD", "Barra de aguante de TrueHUD", "Barra del vigore TrueHUD", "Pasek wytrzymałości TrueHUD", "Lišta výdrže TrueHUD"],
    "HPM_El_TrueHUDOther": ["TrueHUD special bars", "TrueHUD 特殊バー", "TrueHUD 특수 바", "TrueHUD 特殊条", "Особые полосы TrueHUD", "TrueHUD-Sonderleisten",
                            "Barres spéciales TrueHUD", "Barras especiales de TrueHUD", "Barre speciali TrueHUD", "Paski specjalne TrueHUD", "Zvláštní lišty TrueHUD"],
    "HPM_El_WidgetGold": ["Gold widget", "所持金ウィジェット", "골드 위젯", "金币小部件", "Виджет золота", "Gold-Widget", "Widget d'or", "Widget de oro",
                          "Widget dell'oro", "Widżet złota", "Widget zlata"],
    "HPM_El_WidgetWeight": ["Carry weight widget", "所持重量ウィジェット", "소지 무게 위젯", "负重小部件", "Виджет веса", "Traglast-Widget", "Widget de charge",
                            "Widget de peso", "Widget del peso", "Widżet udźwigu", "Widget nosnosti"],
    "HPM_El_WidgetLevel": ["Level widget", "レベルウィジェット", "레벨 위젯", "等级小部件", "Виджет уровня", "Stufen-Widget", "Widget de niveau", "Widget de nivel",
                           "Widget del livello", "Widżet poziomu", "Widget úrovně"],
    "HPM_El_WidgetResist": ["Resistances widget", "耐性ウィジェット", "저항 위젯", "抗性小部件", "Виджет сопротивлений", "Resistenzen-Widget", "Widget des résistances",
                            "Widget de resistencias", "Widget delle resistenze", "Widżet odporności", "Widget odolností"],
    "HPM_El_WidgetEquip": ["Equipment widget", "装備ウィジェット", "장비 위젯", "装备小部件", "Виджет снаряжения", "Ausrüstungs-Widget", "Widget d'équipement",
                           "Widget de equipo", "Widget dell'equipaggiamento", "Widżet ekwipunku", "Widget výbavy"],
    "HPM_El_WidgetShout": ["Shout widget", "シャウトウィジェット", "용언 위젯", "龙吼小部件", "Виджет Крика", "Schrei-Widget", "Widget de cri", "Widget de grito",
                           "Widget dell'urlo", "Widżet okrzyku", "Widget pokřiku"],
    "HPM_El_WidgetGameTime": ["Game time widget", "ゲーム内時刻ウィジェット", "게임 시간 위젯", "游戏时间小部件", "Виджет игрового времени", "Spielzeit-Widget",
                              "Widget de l'heure du jeu", "Widget de hora del juego", "Widget dell'ora di gioco", "Widżet czasu w grze", "Widget herního času"],
    "HPM_El_WidgetPlayTime": ["Play time widget", "プレイ時間ウィジェット", "플레이 시간 위젯", "游玩时长小部件", "Виджет времени игры", "Spieldauer-Widget",
                              "Widget du temps de jeu", "Widget de tiempo jugado", "Widget del tempo di gioco", "Widżet czasu gry", "Widget odehraného času"],
    "HPM_El_WidgetOxygen": ["Oxygen meter", "酸素メーター", "산소 게이지", "氧气条", "Шкала кислорода", "Sauerstoffanzeige", "Jauge d'oxygène", "Medidor de oxígeno",
                            "Indicatore dell'ossigeno", "Wskaźnik tlenu", "Ukazatel kyslíku"],
    "HPM_El_WidgetCasting": ["Casting bar", "詠唱バー", "시전 바", "施法条", "Полоса заклинания", "Zauberleiste", "Barre d'incantation", "Barra de lanzamiento",
                             "Barra di lancio", "Pasek rzucania", "Ukazatel sesílání"],
}
LANGS = ["english", "japanese", "korean", "chinese", "russian", "german", "french", "spanish", "italian", "polish", "czech"]


def or_translations():
    """The Oblivion Remastered version's NEW table (same key names, same language order) - reused where the English matches."""
    src = open(OR_GENDIST, encoding="utf-8").read()
    start = src.index("NEW = {") + len("NEW = ")
    i, depth = start, 0
    while True:
        depth += {"{": 1, "}": -1}.get(src[i], 0)
        i += 1
        if depth == 0:
            break
    return ast.literal_eval(src[start:i])


OR = or_translations()
for k, _ in elements:
    assert f"HPM_El_{k}" in T, f"no translation of the element name HPM_El_{k}"
# every TR("key", "English") in the source: the English must be the table's, and every key must have eleven languages
used = {}
for fn in os.listdir(R + r"\source"):
    if fn.endswith(".cpp"):
        for k, en in re.findall(r'TR\("(HPM_[A-Za-z]+)", "((?:[^"\\]|\\.)*)"\)', open(os.path.join(R, "source", fn), encoding="utf-8").read()):
            used[k] = en
problems = []
for k, en in sorted(used.items()):
    if k in T and T[k][0] == en:
        continue
    if k in OR and OR[k][0] == en:
        T[k] = OR[k]
        continue
    have = T.get(k, OR.get(k, [None]))[0]
    problems.append(f"{k}: source says {en!r}, table says {have!r}")
assert not problems, "translations missing or out of date:\n  " + "\n  ".join(problems)
for i, lang in enumerate(LANGS):
    lines = [f"${k}\t{v[i]}" for k, v in T.items()]
    data = "\ufeff" + "\r\n".join(lines) + "\r\n"
    open(R + rf"\dist\Interface\Translations\HUDPositionManager_{lang}.txt", "wb").write(data.encode("utf-16-le"))
print(len(T), "keys x", len(LANGS), "languages;", len(elements), "elements;", len(used), "keys used in the source")
